version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: meu-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 091820
      MYSQL_DATABASE: meu_banco
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - bridge

volumes:
  mysql-data:
    external: true

networks:
  bridge:
    driver: bridge